"""Turns generated ingredient and dish pictures into game icons for the art sets.

usage: python3 scripts/art/cut.py
reads  .cache/art/styles/<set>-<key>.png  (the style candidates)
       .cache/art/sets/<set>-<key>.png    (full sets, see sets.py; these win)
writes public/art/<set>/<key>.webp, _review/style/img/<set>-<key>.webp and src/ui/art.generated.ts

Every picture is cut out of its plain background and centred optically: halfway between the
middle of its outline and its centre of mass, so a bulb with a thin sprout on top doesn't sink to
the bottom of its chip. Stickers keep their white die-cut border.
"""
import json
import os
import numpy as np
from PIL import Image, ImageFilter

SOURCES = ['.cache/art/styles', '.cache/art/sets']
SETS = ['sticker', 'kawaii', 'watercolor', 'retro']
SIZE = 192
MARGIN = 0.04


def flood(cand):
    """Background = candidate pixels connected to the picture's border."""
    h, w = cand.shape
    mask = np.zeros((h, w), bool)
    stack = [(y, x) for y in (0, h - 1) for x in range(0, w, 3)] + [(y, x) for x in (0, w - 1) for y in range(0, h, 3)]
    while stack:
        y, x = stack.pop()
        if y < 0 or x < 0 or y >= h or x >= w or mask[y, x] or not cand[y, x]:
            continue
        mask[y, x] = True
        stack += [(y + 1, x), (y - 1, x), (y, x + 1), (y, x - 1)]
    return mask


def cut(im, style):
    a = np.array(im.convert('RGBA')).astype(int)
    rgb = a[:, :, :3]
    border = np.concatenate([rgb[0], rgb[-1], rgb[:, 0], rgb[:, -1]])
    bg = np.median(border, axis=0)
    grey = rgb.max(2) - rgb.min(2) < 24
    if style == 'sticker':
        # Light grey background and its soft shadow, but never the white sticker border.
        lum = rgb.mean(2)
        cand = grey & (lum < bg.mean() + 10) & (lum > bg.mean() - 75)
    else:
        near = np.abs(rgb - bg).sum(2) < 34 * 3
        light = (rgb.min(2) > 200) & grey
        cand = near | light
    mask = flood(cand)
    alpha = np.where(mask, 0, 255).astype(np.uint8)
    alpha = np.array(Image.fromarray(alpha).filter(ImageFilter.MinFilter(3)).filter(ImageFilter.GaussianBlur(1.0)))
    a[:, :, 3] = alpha
    return Image.fromarray(a.astype(np.uint8), 'RGBA')


def centre(im):
    """Square crop around the optical centre, with a small margin, resized to SIZE."""
    al = np.array(im)[:, :, 3].astype(float)
    ys, xs = np.where(al > 40)
    if not len(xs):
        return im.resize((SIZE, SIZE), Image.LANCZOS)
    x0, x1, y0, y1 = xs.min(), xs.max() + 1, ys.min(), ys.max() + 1
    bx, by = (x0 + x1) / 2, (y0 + y1) / 2
    wsum = al.sum()
    gy, gx = np.indices(al.shape)
    cx, cy = (gx * al).sum() / wsum, (gy * al).sum() / wsum
    ox, oy = bx + (cx - bx) * 0.5, by + (cy - by) * 0.5
    half = max(x1 - x0, y1 - y0) / 2 + max(abs(ox - bx), abs(oy - by))
    half *= 1 + 2 * MARGIN
    s = int(np.ceil(half * 2))
    sq = Image.new('RGBA', (s, s), (0, 0, 0, 0))
    sq.paste(im, (int(round(s / 2 - ox)), int(round(s / 2 - oy))))
    return sq.resize((SIZE, SIZE), Image.LANCZOS)


def main():
    found = {}
    for src in SOURCES:
        if not os.path.isdir(src):
            continue
        for f in sorted(os.listdir(src)):
            if not f.endswith('.png') or os.path.getsize(os.path.join(src, f)) == 0:
                continue
            style, key = f[:-4].split('-', 1)
            if style in SETS:
                found[(style, key)] = os.path.join(src, f)
    os.makedirs('_review/style/img', exist_ok=True)
    keys = {s: [] for s in SETS}
    for (style, key), path in sorted(found.items()):
        icon = centre(cut(Image.open(path), style))
        os.makedirs(f'public/art/{style}', exist_ok=True)
        icon.save(f'public/art/{style}/{key}.webp', 'WEBP', quality=88, method=6)
        icon.save(f'_review/style/img/{style}-{key}.webp', 'WEBP', quality=88, method=6)
        keys[style].append(key)
    with open('src/ui/art.generated.ts', 'w') as fh:
        fh.write('// Generated by scripts/art/cut.py: which pictures each art set has (public/art/<set>/<key>.webp).\n')
        fh.write(f'export const ART_KEYS: Record<string, readonly string[]> = {json.dumps(keys)};\n')
    print('wrote', sum(len(v) for v in keys.values()), 'icons:', ', '.join(f'{s} {len(v)}' for s, v in keys.items()))


if __name__ == '__main__':
    main()
