/**
 * Extracts Microsoft Fluent Emoji (Flat, MIT license) as inline SVG strings: ingredients, dishes
 * and UI icons. Run: bun scripts/build-icons.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { Resvg } from '@resvg/resvg-js';
import { DISHES, INGREDIENTS, WILD_INFO } from '../src/core/ingredients';
import { CUISINES } from '../src/core/cuisines';

const UI = [
  'light-bulb', 'counterclockwise-arrows-button', 'right-arrow-curving-left', 'star', 'glowing-star', 'locked',
  'unlocked', 'kitchen-knife', 'fire', 'ice', 'snowflake', 'sparkles', 'house', 'gear', 'trophy', 'cross-mark',
  'check-mark-button', 'party-popper', 'bowl-with-spoon', 'oden', 'crown', 'skull', 'red-question-mark',
  'speaker-high-volume', 'muted-speaker', 'musical-note', 'fork-and-knife-with-plate', 'cooking', 'chopsticks',
  'stew', 'hot-beverage', 'pancakes', 'herb', 'four-leaf-clover', 'face-with-spiral-eyes', 'thinking-face',
  'bug', 'clipboard', 'chart-increasing', 'pot-of-food', 'play-button', 'left-arrow', 'clockwise-vertical-arrows',
  'counterclockwise-arrows-button', 'cherry-blossom', 'leafy-green', 'level-slider', 'downwards-button', 'magic-wand',
  'woozy-face', 'smiling-face-with-hearts', 'man-cook', 'woman-cook', 'cook',
  'hot-pepper', 'yarn', 'bellhop-bell', 'jar', 'timer-clock', 'ice', 'pizza', 'sushi', 'taco', 'hamburger', 'curry-rice', 'dumpling',
  // Tips and the market.
  'coin', 'money-bag', 'basket', 'shopping-bags', 'wrapped-gift', 'artist-palette', 'paintbrush',
  // Map scenery props.
  'airplane', 'cloud', 'compass', 'luggage', 'world-map', 'round-pushpin', 'motor-scooter', 'grapes', 'wine-glass', 'sunflower',
  'classical-building', 'japanese-castle', 'shinto-shrine', 'wind-chime', 'teacup-without-handle', 'dango', 'tokyo-tower',
  'folding-hand-fan', 'hibiscus', 'cup-with-straw', 'soft-ice-cream', 'doughnut', 'automobile', 'elephant', 'peacock', 'kite',
  'blossom', 'dragon', 'red-envelope', 'firecracker', 'teapot', 'evergreen-tree', 'deciduous-tree', 'palm-tree', 'sailboat',
  'bamboo', 'dove', 'tulip', 'cherries', 'lemon', 'sun-with-face', 'crescent-moon', 'glowing-star',
];

/**
 * Food icons get a square viewBox around their optical centre (halfway between the middle of the
 * outline and the centre of mass), so a sprig of herbs or a bulb with a sprout sits in the middle
 * of its chip like everything else, at the same visual size.
 */
function opticalBox(svg: string, x0: number, y0: number, w: number): string {
  const img = new Resvg(svg, { fitTo: { mode: 'width', value: 160 } }).render();
  const px = img.pixels;
  const W = img.width;
  const H = img.height;
  let minX = W, minY = H, maxX = -1, maxY = -1, sum = 0, sx = 0, sy = 0;
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    const a = px[(y * W + x) * 4 + 3];
    sum += a;
    sx += a * x;
    sy += a * y;
    if (a > 40) {
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }
  if (maxX < 0) return `${x0} ${y0} ${w} ${w}`;
  const bx = (minX + maxX + 1) / 2;
  const by = (minY + maxY + 1) / 2;
  const ox = bx + (sx / sum - bx) * 0.5;
  const oy = by + (sy / sum - by) * 0.5;
  const half = (Math.max(maxX + 1 - minX, maxY + 1 - minY) / 2 + Math.max(Math.abs(ox - bx), Math.abs(oy - by))) * 1.04;
  const k = w / W;
  const f = (v: number) => +v.toFixed(2);
  return `${f(x0 + (ox - half) * k)} ${f(y0 + (oy - half) * k)} ${f(2 * half * k)} ${f(2 * half * k)}`;
}

const set = JSON.parse(readFileSync('node_modules/@iconify-json/fluent-emoji-flat/icons.json', 'utf8'));
const out: Record<string, string> = {};
const names = new Set([...INGREDIENTS.map((i) => i.icon), ...Object.values(DISHES).map((d) => d.icon), WILD_INFO.icon, ...UI, ...CUISINES.flatMap((c) => [c.icon, ...c.deco])]);
const food = new Set([...INGREDIENTS.map((i) => i.icon), ...Object.values(DISHES).map((d) => d.icon), WILD_INFO.icon]);
const missing: string[] = [];
for (const name of names) {
  let icon = set.icons[name];
  if (!icon && set.aliases?.[name]) icon = set.icons[set.aliases[name].parent];
  if (!icon) {
    missing.push(name);
    continue;
  }
  const w = icon.width ?? set.width;
  const h = icon.height ?? set.height;
  const plain = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${icon.left ?? 0} ${icon.top ?? 0} ${w} ${h}">${icon.body}</svg>`;
  out[name] = food.has(name)
    ? `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${opticalBox(plain, icon.left ?? 0, icon.top ?? 0, w)}">${icon.body}</svg>`
    : plain;
}
const src =
  '// Generated by scripts/build-icons.ts from Microsoft Fluent Emoji (Flat), MIT License.\n' +
  '// https://github.com/microsoft/fluentui-emoji\n' +
  `export const EMOJI: Record<string, string> = ${JSON.stringify(out, null, 0)};\n`;
writeFileSync('src/ui/emoji.generated.ts', src);
console.log('wrote', Object.keys(out).length, 'icons,', src.length, 'bytes', missing.length ? 'missing: ' + missing.join(', ') : '');
