/**
 * Extracts Microsoft Fluent Emoji (Flat, MIT license) as inline SVG strings: ingredients, dishes
 * and UI icons. Run: bun scripts/build-icons.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { DISHES, INGREDIENTS, WILD_INFO } from '../src/core/ingredients';

const UI = [
  'light-bulb', 'counterclockwise-arrows-button', 'right-arrow-curving-left', 'star', 'glowing-star', 'locked',
  'unlocked', 'kitchen-knife', 'fire', 'ice', 'snowflake', 'sparkles', 'house', 'gear', 'trophy', 'cross-mark',
  'check-mark-button', 'party-popper', 'bowl-with-spoon', 'oden', 'crown', 'skull', 'red-question-mark',
  'speaker-high-volume', 'muted-speaker', 'musical-note', 'fork-and-knife-with-plate', 'cooking', 'chopsticks',
  'stew', 'hot-beverage', 'pancakes', 'herb', 'four-leaf-clover', 'face-with-spiral-eyes', 'thinking-face',
  'bug', 'clipboard', 'chart-increasing', 'pot-of-food', 'play-button', 'left-arrow', 'clockwise-vertical-arrows',
  'counterclockwise-arrows-button', 'cherry-blossom', 'leafy-green', 'level-slider', 'downwards-button', 'magic-wand',
  'woozy-face', 'smiling-face-with-hearts', 'man-cook', 'woman-cook', 'cook',
];

const set = JSON.parse(readFileSync('node_modules/@iconify-json/fluent-emoji-flat/icons.json', 'utf8'));
const out: Record<string, string> = {};
const names = new Set([...INGREDIENTS.map((i) => i.icon), ...Object.values(DISHES).map((d) => d.icon), WILD_INFO.icon, ...UI]);
const missing: string[] = [];
for (const name of names) {
  let icon = set.icons[name];
  if (!icon && set.aliases?.[name]) icon = set.icons[set.aliases[name].parent];
  if (!icon) {
    missing.push(name);
    continue;
  }
  const w = icon.width ?? set.width;
  const h = icon.height ?? set.height;
  out[name] = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${icon.left ?? 0} ${icon.top ?? 0} ${w} ${h}">${icon.body}</svg>`;
}
const src =
  '// Generated by scripts/build-icons.ts from Microsoft Fluent Emoji (Flat), MIT License.\n' +
  '// https://github.com/microsoft/fluentui-emoji\n' +
  `export const EMOJI: Record<string, string> = ${JSON.stringify(out, null, 0)};\n`;
writeFileSync('src/ui/emoji.generated.ts', src);
console.log('wrote', Object.keys(out).length, 'icons,', src.length, 'bytes', missing.length ? 'missing: ' + missing.join(', ') : '');
